# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='category',
            field=models.ManyToManyField(to='api.Category'),
        ),
    ]
