# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170808_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='addons',
            field=models.ManyToManyField(blank=True, related_name='_item_addons_+', to='api.Item'),
        ),
    ]
