# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 09:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170808_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='driver_cut',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='driver_payout',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='driver_profit',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='gmv',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='management_cut',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='promo_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Promo'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'not made'), (1, 'pending acceptance'), (2, 'accepted'), (3, 'pending payment approval'), (4, 'completed'), (5, 'cancelled')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='tips',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_cost',
            field=models.FloatField(null=True),
        ),
    ]
