# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 12:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170808_0939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='orders',
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='api.Profile'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_location',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='api.Profile'),
        ),
        migrations.AddField(
            model_name='order',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.School'),
        ),
        migrations.AddField(
            model_name='profile',
            name='latest_delivery_location',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
