# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20170808_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promo',
            name='id',
        ),
        migrations.AlterField(
            model_name='promo',
            name='code',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
    ]
